PlayerHouseF1_MapScripts::
	.byte 0

PlayerHouseF1_EventScript_Wooper_Doll::
	msgbox PlayerHouseF1_Sign_Wooper_Doll_Text, MSGBOX_SIGN
	end

PlayerHouseF1_Sign_Wooper_Doll_Text:
	.string "It's your WOOPER DOLL!$"
	
PlayerHouseF1_EventScript_Porygon2_Doll::
	msgbox PlayerHouseF1_Sign_Porygon2_Doll_Text, MSGBOX_SIGN
	end

PlayerHouseF1_Sign_Porygon2_Doll_Text:
	.string "It's your PORYGON2 DOLL!\p"
	.string "There's food stains on its face\n"
	.string "from when you used to feed it.\p"
	.string "MOM would put it in the washer\n"
	.string "and call it good.$"
	
PlayerHouseF1_EventScript_Magnemite_Doll::
	msgbox PlayerHouseF1_Sign_Magnemite_Doll_Text, MSGBOX_SIGN
	end

PlayerHouseF1_Sign_Magnemite_Doll_Text:
	.string "It's your MAGNEMITE DOLL!$"
	
PlayerHouseF1_EventScript_Window::
	msgbox PlayerHouseF1_Sign_Window_Text, MSGBOX_SIGN
	end

PlayerHouseF1_Sign_Window_Text:
	.string "You looked out the window.\p"
	.string "You can just barely see a cave\n"
	.string "entrance from here.$"
	
PlayerHouseF1_EventScript_Gamecube::
	msgbox PlayerHouseF1_Sign_Gamecube_Text, MSGBOX_SIGN
	end

PlayerHouseF1_Sign_Gamecube_Text:
	.string "It's your Nintendo Gamecube!\p"
	.string "You have a lot of fond memories\n"
	.string "and endured hardships with this\l"
	.string "hand-me-down console.\p"
	.string "You started playing the Gamecube.\p"
	.string "......\p"
	.string "............\p"
	.string "..................\p"
	.string "...Okay, better get going!$"
	
PlayerHouseF1_EventScript_Spiral_Notebook::
	msgbox PlayerHouseF1_Sign_Spiral_Notebook_Text, MSGBOX_SIGN
	end
	
PlayerHouseF1_Sign_Spiral_Notebook_Text:
	.string "You flipped to a page in your\n"
	.string "worn out spiral notebook.\p"
	.string "...$"

