#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 1
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 2
#define HEAL_LOCATION_FRESH_TOWN 3
#define HEAL_LOCATION_HISTOR_TOWN 4
#define HEAL_LOCATION_PROSPECT 5

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
