#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_Overworld
#define MAP_FRESH_TOWN    (0 | (0 << 8))
#define MAP_ROUTE1        (1 | (0 << 8))
#define MAP_ROUTE2        (2 | (0 << 8))
#define MAP_HISTOR_TOWN   (3 | (0 << 8))
#define MAP_ROUTE3        (4 | (0 << 8))
#define MAP_PROSPECT      (5 | (0 << 8))
#define MAP_PROSPECT_MINE (6 | (0 << 8))

// gMapGroup_Freshtown
#define MAP_PLAYER_HOUSE_F1  (0 | (1 << 8))
#define MAP_PLAYER_HOUSE_F0  (1 | (1 << 8))
#define MAP_FRESH_HOUSE1     (2 | (1 << 8))
#define MAP_FRESH_TOWN_CAVE1 (3 | (1 << 8))
#define MAP_PROFESSORS_LAB1  (4 | (1 << 8))
#define MAP_PROFESSORS_LAB2  (5 | (1 << 8))

// gMapGroup_Histortown
#define MAP_HISTORY_SCHOOL                     (0 | (2 << 8))
#define MAP_HISTOR_TOWN_POKEMON_CENTER         (1 | (2 << 8))
#define MAP_HISTOR_TOWN_MART                   (2 | (2 << 8))
#define MAP_HISTOR_TOWN_RIVAL_HOUSE            (3 | (2 << 8))
#define MAP_HISTOR_TOWN_RIVAL_HOUSE_RIVAL_ROOM (4 | (2 << 8))

// gMapGroup_Prospect
#define MAP_PROSPECT_POKEMON_CENTER (0 | (3 << 8))
#define MAP_PROSPECT_MART           (1 | (3 << 8))

// gMapGroup_Caves
#define MAP_PROSPECT_MINE_F1  (0 | (4 << 8))
#define MAP_PROSPECT_MINE_F2  (1 | (4 << 8))
#define MAP_PROSPECT_MINE_F2B (2 | (4 << 8))
#define MAP_ARTISAN_CAVE_1F   (3 | (4 << 8))
#define MAP_ARTISAN_CAVE_B1F  (4 | (4 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (5 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (5 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (5 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (5 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (5 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (5 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (5 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (5 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (5 << 8))
#define MAP_TRADE_CENTER             (25 | (5 << 8))
#define MAP_RECORD_CORNER            (26 | (5 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (5 << 8))
#define MAP_CONTEST_HALL             (28 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (5 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (5 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (5 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (5 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (5 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (40 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (41 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (42 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (43 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (44 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (45 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (46 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (47 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (48 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (49 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (50 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (51 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (52 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (53 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (54 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (55 | (5 << 8))
#define MAP_UNION_ROOM               (56 | (5 << 8))

// gMapGroup_SpecialArea
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (0 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (1 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (2 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (3 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (4 | (6 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (5 | (6 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (6 | (6 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (7 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (8 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (9 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (10 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (11 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (12 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (13 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (14 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (15 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (16 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (17 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (18 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (19 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (20 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (21 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (22 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (23 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (24 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (25 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (26 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (27 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (28 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (29 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (30 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (31 | (6 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (32 | (6 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (33 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (34 | (6 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (35 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (36 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (37 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (38 | (6 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (39 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (40 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (41 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (42 | (6 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (43 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (44 | (6 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (45 | (6 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (46 | (6 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (47 | (6 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (48 | (6 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (49 | (6 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (50 | (6 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (51 | (6 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (52 | (6 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (53 | (6 << 8))
#define MAP_TRAINER_HILL_1F                                 (54 | (6 << 8))
#define MAP_TRAINER_HILL_2F                                 (55 | (6 << 8))
#define MAP_TRAINER_HILL_3F                                 (56 | (6 << 8))
#define MAP_TRAINER_HILL_4F                                 (57 | (6 << 8))
#define MAP_TRAINER_HILL_ROOF                               (58 | (6 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (59 | (6 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (60 | (6 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (61 | (6 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (62 | (6 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (63 | (6 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (64 | (6 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (65 | (6 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (66 | (6 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (67 | (6 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (68 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (69 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (70 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (71 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (72 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (73 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (74 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (75 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (76 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (77 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (78 | (6 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (79 | (6 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (80 | (6 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (81 | (6 << 8))
#define MAP_NONE                                            (82 | (6 << 8))
#define MAP_LITTLEROOT_TOWN                                 (83 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F               (84 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F               (85 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F                   (86 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F                   (87 | (6 << 8))

#define MAP_GROUPS_COUNT 7

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
