#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN              0x00
#define MAPSEC_SOUTHERN_ISLAND              0x01
#define MAPSEC_ROUTE_1                      0x02
#define MAPSEC_ROUTE_2                      0x03
#define MAPSEC_ROUTE_3                      0x04
#define MAPSEC_UNUSED_HOENN_0x05            0x05
#define MAPSEC_UNUSED_HOENN_0x06            0x06
#define MAPSEC_UNUSED_HOENN_0x07            0x07
#define MAPSEC_UNUSED_HOENN_0x08            0x08
#define MAPSEC_UNUSED_HOENN_0x09            0x09
#define MAPSEC_UNUSED_HOENN_0x0A            0x0A
#define MAPSEC_UNUSED_HOENN_0x0B            0x0B
#define MAPSEC_UNUSED_HOENN_0x0C            0x0C
#define MAPSEC_UNUSED_HOENN_0x0D            0x0D
#define MAPSEC_UNUSED_HOENN_0x0E            0x0E
#define MAPSEC_UNUSED_HOENN_0x0F            0x0F
#define MAPSEC_UNUSED_HOENN_0x10            0x10
#define MAPSEC_UNUSED_HOENN_0x11            0x11
#define MAPSEC_UNUSED_HOENN_0x12            0x12
#define MAPSEC_UNUSED_HOENN_0x13            0x13
#define MAPSEC_UNUSED_HOENN_0x14            0x14
#define MAPSEC_UNUSED_HOENN_0x15            0x15
#define MAPSEC_UNUSED_HOENN_0x16            0x16
#define MAPSEC_UNUSED_HOENN_0x17            0x17
#define MAPSEC_UNUSED_HOENN_0x18            0x18
#define MAPSEC_UNUSED_HOENN_0x19            0x19
#define MAPSEC_UNUSED_HOENN_0x1A            0x1A
#define MAPSEC_UNUSED_HOENN_0x1B            0x1B
#define MAPSEC_UNUSED_HOENN_0x1C            0x1C
#define MAPSEC_UNUSED_HOENN_0x1D            0x1D
#define MAPSEC_UNUSED_HOENN_0x1E            0x1E
#define MAPSEC_UNUSED_HOENN_0x1F            0x1F
#define MAPSEC_UNUSED_HOENN_0x20            0x20
#define MAPSEC_UNUSED_HOENN_0x21            0x21
#define MAPSEC_UNUSED_HOENN_0x22            0x22
#define MAPSEC_UNUSED_HOENN_0x23            0x23
#define MAPSEC_UNUSED_HOENN_0x24            0x24
#define MAPSEC_UNUSED_HOENN_0x25            0x25
#define MAPSEC_UNUSED_HOENN_0x26            0x26
#define MAPSEC_UNUSED_HOENN_0x27            0x27
#define MAPSEC_UNUSED_HOENN_0x28            0x28
#define MAPSEC_UNUSED_HOENN_0x29            0x29
#define MAPSEC_UNUSED_HOENN_0x2A            0x2A
#define MAPSEC_UNUSED_HOENN_0x2B            0x2B
#define MAPSEC_UNUSED_HOENN_0x2C            0x2C
#define MAPSEC_UNUSED_HOENN_0x2D            0x2D
#define MAPSEC_UNUSED_HOENN_0x2E            0x2E
#define MAPSEC_UNUSED_HOENN_0x2F            0x2F
#define MAPSEC_UNUSED_HOENN_0x30            0x30
#define MAPSEC_UNUSED_HOENN_0x31            0x31
#define MAPSEC_UNUSED_HOENN_0x32            0x32
#define MAPSEC_UNUSED_HOENN_0x33            0x33
#define MAPSEC_UNUSED_HOENN_0x34            0x34
#define MAPSEC_UNUSED_HOENN_0x35            0x35
#define MAPSEC_UNUSED_HOENN_0x36            0x36
#define MAPSEC_UNUSED_HOENN_0x37            0x37
#define MAPSEC_UNUSED_HOENN_0x38            0x38
#define MAPSEC_UNUSED_HOENN_0x39            0x39
#define MAPSEC_UNUSED_HOENN_0x3A            0x3A
#define MAPSEC_UNUSED_HOENN_0x3B            0x3B
#define MAPSEC_UNUSED_HOENN_0x3C            0x3C
#define MAPSEC_UNUSED_HOENN_0x3D            0x3D
#define MAPSEC_UNUSED_HOENN_0x3E            0x3E
#define MAPSEC_UNUSED_HOENN_0x3F            0x3F
#define MAPSEC_UNUSED_HOENN_0x40            0x40
#define MAPSEC_UNUSED_HOENN_0x41            0x41
#define MAPSEC_UNUSED_HOENN_0x42            0x42
#define MAPSEC_UNUSED_HOENN_0x43            0x43
#define MAPSEC_UNUSED_HOENN_0x44            0x44
#define MAPSEC_UNUSED_HOENN_0x45            0x45
#define MAPSEC_UNUSED_HOENN_0x46            0x46
#define MAPSEC_UNUSED_HOENN_0x47            0x47
#define MAPSEC_UNUSED_HOENN_0x48            0x48
#define MAPSEC_UNUSED_HOENN_0x49            0x49
#define MAPSEC_UNUSED_HOENN_0x4A            0x4A
#define MAPSEC_UNUSED_HOENN_0x4B            0x4B
#define MAPSEC_UNUSED_HOENN_0x4C            0x4C
#define MAPSEC_UNUSED_HOENN_0x4D            0x4D
#define MAPSEC_UNUSED_HOENN_0x4E            0x4E
#define MAPSEC_UNUSED_HOENN_0x4F            0x4F
#define MAPSEC_UNUSED_HOENN_0x50            0x50
#define MAPSEC_UNUSED_HOENN_0x51            0x51
#define MAPSEC_UNUSED_HOENN_0x52            0x52
#define MAPSEC_UNUSED_HOENN_0x53            0x53
#define MAPSEC_SAFARI_ZONE                  0x54
#define MAPSEC_BATTLE_FRONTIER              0x55
#define MAPSEC_SECRET_BASE                  0x56
#define MAPSEC_DYNAMIC                      0x57
#define MAPSEC_PALLET_TOWN                  0x58
#define MAPSEC_UNUSED_KANTO_0x59            0x59
#define MAPSEC_UNUSED_KANTO_0x5A            0x5A
#define MAPSEC_UNUSED_KANTO_0x5B            0x5B
#define MAPSEC_UNUSED_KANTO_0x5C            0x5C
#define MAPSEC_UNUSED_KANTO_0x5D            0x5D
#define MAPSEC_UNUSED_KANTO_0x5E            0x5E
#define MAPSEC_UNUSED_KANTO_0x5F            0x5F
#define MAPSEC_UNUSED_KANTO_0x60            0x60
#define MAPSEC_UNUSED_KANTO_0x61            0x61
#define MAPSEC_UNUSED_KANTO_0x62            0x62
#define MAPSEC_UNUSED_KANTO_0x63            0x63
#define MAPSEC_UNUSED_KANTO_0x64            0x64
#define MAPSEC_UNUSED_KANTO_0x65            0x65
#define MAPSEC_UNUSED_KANTO_0x66            0x66
#define MAPSEC_UNUSED_KANTO_0x67            0x67
#define MAPSEC_UNUSED_KANTO_0x68            0x68
#define MAPSEC_UNUSED_KANTO_0x69            0x69
#define MAPSEC_UNUSED_KANTO_0x6A            0x6A
#define MAPSEC_UNUSED_KANTO_0x6B            0x6B
#define MAPSEC_UNUSED_KANTO_0x6C            0x6C
#define MAPSEC_UNUSED_KANTO_0x6D            0x6D
#define MAPSEC_UNUSED_KANTO_0x6E            0x6E
#define MAPSEC_UNUSED_KANTO_0x6F            0x6F
#define MAPSEC_UNUSED_KANTO_0x70            0x70
#define MAPSEC_UNUSED_KANTO_0x71            0x71
#define MAPSEC_UNUSED_KANTO_0x72            0x72
#define MAPSEC_UNUSED_KANTO_0x73            0x73
#define MAPSEC_UNUSED_KANTO_0x74            0x74
#define MAPSEC_UNUSED_KANTO_0x75            0x75
#define MAPSEC_UNUSED_KANTO_0x76            0x76
#define MAPSEC_UNUSED_KANTO_0x77            0x77
#define MAPSEC_UNUSED_KANTO_0x78            0x78
#define MAPSEC_UNUSED_KANTO_0x79            0x79
#define MAPSEC_UNUSED_KANTO_0x7A            0x7A
#define MAPSEC_UNUSED_KANTO_0x7B            0x7B
#define MAPSEC_UNUSED_KANTO_0x7C            0x7C
#define MAPSEC_UNUSED_KANTO_0x7D            0x7D
#define MAPSEC_UNUSED_KANTO_0x7E            0x7E
#define MAPSEC_UNUSED_KANTO_0x7F            0x7F
#define MAPSEC_UNUSED_KANTO_0x80            0x80
#define MAPSEC_UNUSED_KANTO_0x81            0x81
#define MAPSEC_UNUSED_KANTO_0x82            0x82
#define MAPSEC_UNUSED_KANTO_0x83            0x83
#define MAPSEC_UNUSED_KANTO_0x84            0x84
#define MAPSEC_UNUSED_KANTO_0x85            0x85
#define MAPSEC_UNUSED_KANTO_0x86            0x86
#define MAPSEC_UNUSED_KANTO_0x87            0x87
#define MAPSEC_UNUSED_KANTO_0x88            0x88
#define MAPSEC_UNUSED_KANTO_0x89            0x89
#define MAPSEC_UNUSED_KANTO_0x8A            0x8A
#define MAPSEC_UNUSED_KANTO_0x8B            0x8B
#define MAPSEC_UNUSED_KANTO_0x8C            0x8C
#define MAPSEC_UNUSED_KANTO_0x8D            0x8D
#define MAPSEC_UNUSED_KANTO_0x8E            0x8E
#define MAPSEC_UNUSED_KANTO_0x8F            0x8F
#define MAPSEC_UNUSED_KANTO_0x90            0x90
#define MAPSEC_UNUSED_KANTO_0x91            0x91
#define MAPSEC_UNUSED_KANTO_0x92            0x92
#define MAPSEC_UNUSED_KANTO_0x93            0x93
#define MAPSEC_UNUSED_KANTO_0x94            0x94
#define MAPSEC_UNUSED_KANTO_0x95            0x95
#define MAPSEC_UNUSED_KANTO_0x96            0x96
#define MAPSEC_UNUSED_KANTO_0x97            0x97
#define MAPSEC_UNUSED_KANTO_0x98            0x98
#define MAPSEC_UNUSED_KANTO_0x99            0x99
#define MAPSEC_UNUSED_KANTO_0x9A            0x9A
#define MAPSEC_UNUSED_KANTO_0x9B            0x9B
#define MAPSEC_UNUSED_KANTO_0x9C            0x9C
#define MAPSEC_UNUSED_KANTO_0x9D            0x9D
#define MAPSEC_UNUSED_KANTO_0x9E            0x9E
#define MAPSEC_UNUSED_KANTO_0x9F            0x9F
#define MAPSEC_UNUSED_KANTO_0xA0            0xA0
#define MAPSEC_UNUSED_KANTO_0xA1            0xA1
#define MAPSEC_UNUSED_KANTO_0xA2            0xA2
#define MAPSEC_UNUSED_KANTO_0xA3            0xA3
#define MAPSEC_UNUSED_KANTO_0xA4            0xA4
#define MAPSEC_UNUSED_KANTO_0xA5            0xA5
#define MAPSEC_UNUSED_KANTO_0xA6            0xA6
#define MAPSEC_UNUSED_KANTO_0xA7            0xA7
#define MAPSEC_UNUSED_KANTO_0xA8            0xA8
#define MAPSEC_UNUSED_KANTO_0xA9            0xA9
#define MAPSEC_UNUSED_KANTO_0xAA            0xAA
#define MAPSEC_UNUSED_KANTO_0xAB            0xAB
#define MAPSEC_UNUSED_KANTO_0xAC            0xAC
#define MAPSEC_UNUSED_KANTO_0xAD            0xAD
#define MAPSEC_UNUSED_KANTO_0xAE            0xAE
#define MAPSEC_UNUSED_KANTO_0xAF            0xAF
#define MAPSEC_UNUSED_KANTO_0xB0            0xB0
#define MAPSEC_UNUSED_KANTO_0xB1            0xB1
#define MAPSEC_UNUSED_KANTO_0xB2            0xB2
#define MAPSEC_UNUSED_KANTO_0xB3            0xB3
#define MAPSEC_UNUSED_KANTO_0xB4            0xB4
#define MAPSEC_UNUSED_KANTO_0xB5            0xB5
#define MAPSEC_UNUSED_KANTO_0xB6            0xB6
#define MAPSEC_UNUSED_KANTO_0xB7            0xB7
#define MAPSEC_UNUSED_KANTO_0xB8            0xB8
#define MAPSEC_UNUSED_KANTO_0xB9            0xB9
#define MAPSEC_UNUSED_KANTO_0xBA            0xBA
#define MAPSEC_UNUSED_KANTO_0xBB            0xBB
#define MAPSEC_UNUSED_KANTO_0xBC            0xBC
#define MAPSEC_UNUSED_KANTO_0xBD            0xBD
#define MAPSEC_UNUSED_KANTO_0xBE            0xBE
#define MAPSEC_UNUSED_KANTO_0xBF            0xBF
#define MAPSEC_UNUSED_KANTO_0xC0            0xC0
#define MAPSEC_UNUSED_KANTO_0xC1            0xC1
#define MAPSEC_UNUSED_KANTO_0xC2            0xC2
#define MAPSEC_UNUSED_KANTO_0xC3            0xC3
#define MAPSEC_SPECIAL_AREA                 0xC4
#define MAPSEC_AQUA_HIDEOUT                 0xC5
#define MAPSEC_MAGMA_HIDEOUT                0xC6
#define MAPSEC_MIRAGE_TOWER                 0xC7
#define MAPSEC_BIRTH_ISLAND                 0xC8
#define MAPSEC_FARAWAY_ISLAND               0xC9
#define MAPSEC_ARTISAN_CAVE                 0xCA
#define MAPSEC_MARINE_CAVE                  0xCB
#define MAPSEC_UNDERWATER_MARINE_CAVE       0xCC
#define MAPSEC_TERRA_CAVE                   0xCD
#define MAPSEC_UNDERWATER_105               0xCE
#define MAPSEC_UNDERWATER_125               0xCF
#define MAPSEC_UNDERWATER_129               0xD0
#define MAPSEC_DESERT_UNDERPASS             0xD1
#define MAPSEC_ALTERING_CAVE                0xD2
#define MAPSEC_NAVEL_ROCK                   0xD3
#define MAPSEC_TRAINER_HILL                 0xD4
#define MAPSEC_NONE_OLD                     0xD5
#define MAPSEC_FRESH_TOWN					0xD6
#define MAPSEC_HISTOR_TOWN					0xD7
#define MAPSEC_PROSPECT						0xD8
#define MAPSEC_PROSPECT_MINE				0xD9
#define MAPSEC_NONE                         0xDA

#define METLOC_SPECIAL_EGG                  0xFD
#define METLOC_IN_GAME_TRADE                0xFE
#define METLOC_FATEFUL_ENCOUNTER            0xFF

#define KANTO_MAPSEC_START  MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
