HistorySchool_MapScripts::
	.byte 0


HistorySchool_Teacher::
	lock
	faceplayer
	msgbox HistorySchool_Teacher_Dia, MSGBOX_DEFAULT
	release
end

HistorySchool_Teacher_Dia:
	.string "Placeholder$"


HistorySchool_Student_1::
	lock
	faceplayer
	msgbox HistorySchool_Student_1_Dia, MSGBOX_DEFAULT
	release
end

HistorySchool_Student_1_Dia:
	.string "Placeholder1$"


HistorySchool_Student_2::
	lock
	faceplayer
	msgbox HistorySchool_Student_2_Dia, MSGBOX_DEFAULT
	release
end

HistorySchool_Student_2_Dia:
	.string "Placeholder2$"


HistorySchool_Student_3::
	lock
	faceplayer
	msgbox HistorySchool_Student_3_Dia, MSGBOX_DEFAULT
	release
end

HistorySchool_Student_3_Dia:
	.string "Placeholder3$"


HistorySchool_Student_4::
	lock
	faceplayer
	msgbox HistorySchool_Student_4_Dia, MSGBOX_DEFAULT
	release
end

HistorySchool_Student_4_Dia:
	.string "Placeholder4$"
